// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransportRouteApi.Data;

#nullable disable

namespace TransportRouteApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260317044408_InitialTransjakartaSeed")]
    partial class InitialTransjakartaSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TransportRouteApi.Models.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryName = "BRT"
                        },
                        new
                        {
                            Id = 2L,
                            CategoryName = "Non-BRT (MetroTrans)"
                        },
                        new
                        {
                            Id = 3L,
                            CategoryName = "Mikrotrans"
                        });
                });

            modelBuilder.Entity("TransportRouteApi.Models.TransitRoute", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("EndingHour")
                        .HasColumnType("time");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("StartingHour")
                        .HasColumnType("time");

                    b.Property<string>("StartingPoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TransitRoutes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Destination = "Kota",
                            EndingHour = new TimeOnly(22, 0, 0),
                            RouteName = "Corridor 1",
                            StartingHour = new TimeOnly(5, 0, 0),
                            StartingPoint = "Blok M"
                        },
                        new
                        {
                            Id = 2L,
                            Destination = "Monas",
                            EndingHour = new TimeOnly(22, 0, 0),
                            RouteName = "Corridor 2",
                            StartingHour = new TimeOnly(5, 0, 0),
                            StartingPoint = "Pulo Gadung 1"
                        },
                        new
                        {
                            Id = 3L,
                            Destination = "Pasar Baru",
                            EndingHour = new TimeOnly(22, 0, 0),
                            RouteName = "Corridor 3",
                            StartingHour = new TimeOnly(5, 0, 0),
                            StartingPoint = "Kalideres"
                        },
                        new
                        {
                            Id = 4L,
                            Destination = "Dukuh Atas 2",
                            EndingHour = new TimeOnly(22, 0, 0),
                            RouteName = "Corridor 4",
                            StartingHour = new TimeOnly(5, 0, 0),
                            StartingPoint = "Pulo Gadung 2"
                        },
                        new
                        {
                            Id = 5L,
                            Destination = "Ancol",
                            EndingHour = new TimeOnly(22, 0, 0),
                            RouteName = "Corridor 5",
                            StartingHour = new TimeOnly(5, 0, 0),
                            StartingPoint = "Kampung Melayu"
                        },
                        new
                        {
                            Id = 6L,
                            Destination = "Dukuh Atas 2",
                            EndingHour = new TimeOnly(22, 0, 0),
                            RouteName = "Corridor 6",
                            StartingHour = new TimeOnly(5, 0, 0),
                            StartingPoint = "Ragunan"
                        },
                        new
                        {
                            Id = 7L,
                            Destination = "Kampung Melayu",
                            EndingHour = new TimeOnly(22, 0, 0),
                            RouteName = "Corridor 7",
                            StartingHour = new TimeOnly(5, 0, 0),
                            StartingPoint = "Kampung Rambutan"
                        },
                        new
                        {
                            Id = 8L,
                            Destination = "Pasar Baru",
                            EndingHour = new TimeOnly(22, 0, 0),
                            RouteName = "Corridor 8",
                            StartingHour = new TimeOnly(5, 0, 0),
                            StartingPoint = "Lebak Bulus"
                        },
                        new
                        {
                            Id = 9L,
                            Destination = "Pluit",
                            EndingHour = new TimeOnly(22, 0, 0),
                            RouteName = "Corridor 9",
                            StartingHour = new TimeOnly(5, 0, 0),
                            StartingPoint = "Pinang Ranti"
                        },
                        new
                        {
                            Id = 10L,
                            Destination = "PGC 2",
                            EndingHour = new TimeOnly(22, 0, 0),
                            RouteName = "Corridor 10",
                            StartingHour = new TimeOnly(5, 0, 0),
                            StartingPoint = "Tanjung Priok"
                        },
                        new
                        {
                            Id = 11L,
                            Destination = "Kampung Melayu",
                            EndingHour = new TimeOnly(22, 0, 0),
                            RouteName = "Corridor 11",
                            StartingHour = new TimeOnly(5, 0, 0),
                            StartingPoint = "Pulo Gebang"
                        },
                        new
                        {
                            Id = 12L,
                            Destination = "Sunter Kelapa Gading",
                            EndingHour = new TimeOnly(22, 0, 0),
                            RouteName = "Corridor 12",
                            StartingHour = new TimeOnly(5, 0, 0),
                            StartingPoint = "Penjaringan"
                        },
                        new
                        {
                            Id = 13L,
                            Destination = "Tendean",
                            EndingHour = new TimeOnly(22, 0, 0),
                            RouteName = "Corridor 13",
                            StartingHour = new TimeOnly(5, 0, 0),
                            StartingPoint = "Ciledug"
                        },
                        new
                        {
                            Id = 14L,
                            Destination = "Senen",
                            EndingHour = new TimeOnly(22, 0, 0),
                            RouteName = "Corridor 14",
                            StartingHour = new TimeOnly(5, 0, 0),
                            StartingPoint = "JIS"
                        },
                        new
                        {
                            Id = 15L,
                            Destination = "Balai Kota",
                            EndingHour = new TimeOnly(22, 0, 0),
                            RouteName = "Route 1A",
                            StartingHour = new TimeOnly(5, 0, 0),
                            StartingPoint = "PIK"
                        },
                        new
                        {
                            Id = 16L,
                            Destination = "Blok M",
                            EndingHour = new TimeOnly(22, 0, 0),
                            RouteName = "Route 1P",
                            StartingHour = new TimeOnly(5, 0, 0),
                            StartingPoint = "Senen"
                        },
                        new
                        {
                            Id = 17L,
                            Destination = "Bundaran HI",
                            EndingHour = new TimeOnly(22, 0, 0),
                            RouteName = "Route 1V",
                            StartingHour = new TimeOnly(5, 0, 0),
                            StartingPoint = "Lebak Bulus"
                        },
                        new
                        {
                            Id = 18L,
                            Destination = "Rawa Buaya",
                            EndingHour = new TimeOnly(22, 0, 0),
                            RouteName = "Route 2A",
                            StartingHour = new TimeOnly(5, 0, 0),
                            StartingPoint = "Pulo Gadung 1"
                        },
                        new
                        {
                            Id = 19L,
                            Destination = "Senen",
                            EndingHour = new TimeOnly(22, 0, 0),
                            RouteName = "Route 2P",
                            StartingHour = new TimeOnly(5, 0, 0),
                            StartingPoint = "Gondangdia"
                        },
                        new
                        {
                            Id = 20L,
                            Destination = "Balai Kota",
                            EndingHour = new TimeOnly(22, 0, 0),
                            RouteName = "Route 2Q",
                            StartingHour = new TimeOnly(5, 0, 0),
                            StartingPoint = "Gondangdia"
                        },
                        new
                        {
                            Id = 21L,
                            Destination = "Sentraland Cengkareng",
                            EndingHour = new TimeOnly(22, 0, 0),
                            RouteName = "Route 3E",
                            StartingHour = new TimeOnly(5, 0, 0),
                            StartingPoint = "Puri Kembangan"
                        },
                        new
                        {
                            Id = 22L,
                            Destination = "UI",
                            EndingHour = new TimeOnly(22, 0, 0),
                            RouteName = "Route 4B",
                            StartingHour = new TimeOnly(5, 0, 0),
                            StartingPoint = "Stasiun Manggarai"
                        },
                        new
                        {
                            Id = 23L,
                            Destination = "Bundaran Senayan",
                            EndingHour = new TimeOnly(22, 0, 0),
                            RouteName = "Route 4C",
                            StartingHour = new TimeOnly(5, 0, 0),
                            StartingPoint = "TU Gas"
                        },
                        new
                        {
                            Id = 24L,
                            Destination = "Juanda",
                            EndingHour = new TimeOnly(22, 0, 0),
                            RouteName = "Route 5C",
                            StartingHour = new TimeOnly(5, 0, 0),
                            StartingPoint = "PGC 1"
                        },
                        new
                        {
                            Id = 25L,
                            Destination = "Tanah Abang",
                            EndingHour = new TimeOnly(22, 0, 0),
                            RouteName = "Route 5M",
                            StartingHour = new TimeOnly(5, 0, 0),
                            StartingPoint = "Kampung Melayu"
                        },
                        new
                        {
                            Id = 26L,
                            Destination = "Monas via Kuningan",
                            EndingHour = new TimeOnly(22, 0, 0),
                            RouteName = "Route 6A",
                            StartingHour = new TimeOnly(5, 0, 0),
                            StartingPoint = "Ragunan"
                        },
                        new
                        {
                            Id = 27L,
                            Destination = "Monas via Semanggi",
                            EndingHour = new TimeOnly(22, 0, 0),
                            RouteName = "Route 6B",
                            StartingHour = new TimeOnly(5, 0, 0),
                            StartingPoint = "Ragunan"
                        },
                        new
                        {
                            Id = 28L,
                            Destination = "Karet via Patra Kuningan",
                            EndingHour = new TimeOnly(22, 0, 0),
                            RouteName = "Route 6C",
                            StartingHour = new TimeOnly(5, 0, 0),
                            StartingPoint = "Stasiun Tebet"
                        },
                        new
                        {
                            Id = 29L,
                            Destination = "Bundaran Senayan",
                            EndingHour = new TimeOnly(22, 0, 0),
                            RouteName = "Route 6D",
                            StartingHour = new TimeOnly(5, 0, 0),
                            StartingPoint = "Stasiun Tebet"
                        },
                        new
                        {
                            Id = 30L,
                            Destination = "Lebak Bulus",
                            EndingHour = new TimeOnly(22, 0, 0),
                            RouteName = "Route 7A",
                            StartingHour = new TimeOnly(5, 0, 0),
                            StartingPoint = "Kampung Rambutan"
                        });
                });

            modelBuilder.Entity("TransportRouteApi.Models.Vehicle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<long>("TransitRouteId")
                        .HasColumnType("bigint");

                    b.Property<string>("VehicleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TransitRouteId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryId = 2L,
                            TransitRouteId = 2L,
                            VehicleName = "SAF-001"
                        },
                        new
                        {
                            Id = 2L,
                            CategoryId = 3L,
                            TransitRouteId = 3L,
                            VehicleName = "MYS-002"
                        },
                        new
                        {
                            Id = 3L,
                            CategoryId = 1L,
                            TransitRouteId = 4L,
                            VehicleName = "BMP-003"
                        },
                        new
                        {
                            Id = 4L,
                            CategoryId = 2L,
                            TransitRouteId = 5L,
                            VehicleName = "TJ-004"
                        },
                        new
                        {
                            Id = 5L,
                            CategoryId = 3L,
                            TransitRouteId = 6L,
                            VehicleName = "SAF-005"
                        },
                        new
                        {
                            Id = 6L,
                            CategoryId = 1L,
                            TransitRouteId = 7L,
                            VehicleName = "MYS-006"
                        },
                        new
                        {
                            Id = 7L,
                            CategoryId = 2L,
                            TransitRouteId = 8L,
                            VehicleName = "BMP-007"
                        },
                        new
                        {
                            Id = 8L,
                            CategoryId = 3L,
                            TransitRouteId = 9L,
                            VehicleName = "TJ-008"
                        },
                        new
                        {
                            Id = 9L,
                            CategoryId = 1L,
                            TransitRouteId = 10L,
                            VehicleName = "SAF-009"
                        },
                        new
                        {
                            Id = 10L,
                            CategoryId = 2L,
                            TransitRouteId = 11L,
                            VehicleName = "MYS-010"
                        },
                        new
                        {
                            Id = 11L,
                            CategoryId = 3L,
                            TransitRouteId = 12L,
                            VehicleName = "BMP-011"
                        },
                        new
                        {
                            Id = 12L,
                            CategoryId = 1L,
                            TransitRouteId = 13L,
                            VehicleName = "TJ-012"
                        },
                        new
                        {
                            Id = 13L,
                            CategoryId = 2L,
                            TransitRouteId = 14L,
                            VehicleName = "SAF-013"
                        },
                        new
                        {
                            Id = 14L,
                            CategoryId = 3L,
                            TransitRouteId = 15L,
                            VehicleName = "MYS-014"
                        },
                        new
                        {
                            Id = 15L,
                            CategoryId = 1L,
                            TransitRouteId = 16L,
                            VehicleName = "BMP-015"
                        },
                        new
                        {
                            Id = 16L,
                            CategoryId = 2L,
                            TransitRouteId = 17L,
                            VehicleName = "TJ-016"
                        },
                        new
                        {
                            Id = 17L,
                            CategoryId = 3L,
                            TransitRouteId = 18L,
                            VehicleName = "SAF-017"
                        },
                        new
                        {
                            Id = 18L,
                            CategoryId = 1L,
                            TransitRouteId = 19L,
                            VehicleName = "MYS-018"
                        },
                        new
                        {
                            Id = 19L,
                            CategoryId = 2L,
                            TransitRouteId = 20L,
                            VehicleName = "BMP-019"
                        },
                        new
                        {
                            Id = 20L,
                            CategoryId = 3L,
                            TransitRouteId = 21L,
                            VehicleName = "TJ-020"
                        },
                        new
                        {
                            Id = 21L,
                            CategoryId = 1L,
                            TransitRouteId = 22L,
                            VehicleName = "SAF-021"
                        },
                        new
                        {
                            Id = 22L,
                            CategoryId = 2L,
                            TransitRouteId = 23L,
                            VehicleName = "MYS-022"
                        },
                        new
                        {
                            Id = 23L,
                            CategoryId = 3L,
                            TransitRouteId = 24L,
                            VehicleName = "BMP-023"
                        },
                        new
                        {
                            Id = 24L,
                            CategoryId = 1L,
                            TransitRouteId = 25L,
                            VehicleName = "TJ-024"
                        },
                        new
                        {
                            Id = 25L,
                            CategoryId = 2L,
                            TransitRouteId = 26L,
                            VehicleName = "SAF-025"
                        },
                        new
                        {
                            Id = 26L,
                            CategoryId = 3L,
                            TransitRouteId = 27L,
                            VehicleName = "MYS-026"
                        },
                        new
                        {
                            Id = 27L,
                            CategoryId = 1L,
                            TransitRouteId = 28L,
                            VehicleName = "BMP-027"
                        },
                        new
                        {
                            Id = 28L,
                            CategoryId = 2L,
                            TransitRouteId = 29L,
                            VehicleName = "TJ-028"
                        },
                        new
                        {
                            Id = 29L,
                            CategoryId = 3L,
                            TransitRouteId = 30L,
                            VehicleName = "SAF-029"
                        },
                        new
                        {
                            Id = 30L,
                            CategoryId = 1L,
                            TransitRouteId = 1L,
                            VehicleName = "MYS-030"
                        },
                        new
                        {
                            Id = 31L,
                            CategoryId = 2L,
                            TransitRouteId = 2L,
                            VehicleName = "BMP-031"
                        },
                        new
                        {
                            Id = 32L,
                            CategoryId = 3L,
                            TransitRouteId = 3L,
                            VehicleName = "TJ-032"
                        },
                        new
                        {
                            Id = 33L,
                            CategoryId = 1L,
                            TransitRouteId = 4L,
                            VehicleName = "SAF-033"
                        },
                        new
                        {
                            Id = 34L,
                            CategoryId = 2L,
                            TransitRouteId = 5L,
                            VehicleName = "MYS-034"
                        },
                        new
                        {
                            Id = 35L,
                            CategoryId = 3L,
                            TransitRouteId = 6L,
                            VehicleName = "BMP-035"
                        },
                        new
                        {
                            Id = 36L,
                            CategoryId = 1L,
                            TransitRouteId = 7L,
                            VehicleName = "TJ-036"
                        },
                        new
                        {
                            Id = 37L,
                            CategoryId = 2L,
                            TransitRouteId = 8L,
                            VehicleName = "SAF-037"
                        },
                        new
                        {
                            Id = 38L,
                            CategoryId = 3L,
                            TransitRouteId = 9L,
                            VehicleName = "MYS-038"
                        },
                        new
                        {
                            Id = 39L,
                            CategoryId = 1L,
                            TransitRouteId = 10L,
                            VehicleName = "BMP-039"
                        },
                        new
                        {
                            Id = 40L,
                            CategoryId = 2L,
                            TransitRouteId = 11L,
                            VehicleName = "TJ-040"
                        },
                        new
                        {
                            Id = 41L,
                            CategoryId = 3L,
                            TransitRouteId = 12L,
                            VehicleName = "SAF-041"
                        },
                        new
                        {
                            Id = 42L,
                            CategoryId = 1L,
                            TransitRouteId = 13L,
                            VehicleName = "MYS-042"
                        },
                        new
                        {
                            Id = 43L,
                            CategoryId = 2L,
                            TransitRouteId = 14L,
                            VehicleName = "BMP-043"
                        },
                        new
                        {
                            Id = 44L,
                            CategoryId = 3L,
                            TransitRouteId = 15L,
                            VehicleName = "TJ-044"
                        },
                        new
                        {
                            Id = 45L,
                            CategoryId = 1L,
                            TransitRouteId = 16L,
                            VehicleName = "SAF-045"
                        },
                        new
                        {
                            Id = 46L,
                            CategoryId = 2L,
                            TransitRouteId = 17L,
                            VehicleName = "MYS-046"
                        },
                        new
                        {
                            Id = 47L,
                            CategoryId = 3L,
                            TransitRouteId = 18L,
                            VehicleName = "BMP-047"
                        },
                        new
                        {
                            Id = 48L,
                            CategoryId = 1L,
                            TransitRouteId = 19L,
                            VehicleName = "TJ-048"
                        },
                        new
                        {
                            Id = 49L,
                            CategoryId = 2L,
                            TransitRouteId = 20L,
                            VehicleName = "SAF-049"
                        },
                        new
                        {
                            Id = 50L,
                            CategoryId = 3L,
                            TransitRouteId = 21L,
                            VehicleName = "MYS-050"
                        });
                });

            modelBuilder.Entity("TransportRouteApi.Models.Vehicle", b =>
                {
                    b.HasOne("TransportRouteApi.Models.Category", "Category")
                        .WithMany("Vehicles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TransportRouteApi.Models.TransitRoute", "TransitRoute")
                        .WithMany("Vehicles")
                        .HasForeignKey("TransitRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("TransitRoute");
                });

            modelBuilder.Entity("TransportRouteApi.Models.Category", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("TransportRouteApi.Models.TransitRoute", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
